alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: os.oxy.so
  type: PRIMARY
  zone: oxy.so
  wildcard: true
name: oxyos-website
region: tor
static_sites:
- name: oxyos-website
  github:
    branch: master
    deploy_on_push: true
    repo: OxyHQ/OxyOS-website
  dockerfile_path: Dockerfile
  output_dir: /everything
